#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Resume
domain: mitchellballer.com
url: https://mitchellballer.com
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"


# Development Settings
port: 4000
host: 0.0.0.0
safe: false